Managed status bar color based on theme mode
Insight-Timer/modal_bottom_sheet pull request #1
Opened 2021-01-08 10:13 UTC by prayan-patel

- Displayed status bar based on theme mode by default it value is false for night mode.

2021-01-08 10:14 UTC, vishnunew approved these changes

2021-01-11 11:44 UTC, onikiri2007 reviewed
Instead of hard coding it. Can u make it to be able to set colors through themeData or via parameter

2021-01-11 23:45 UTC, onikiri2007 requested changes

2021-01-11 23:45 UTC, onikiri2007 commented on lib/src/bottom_sheets/cupertino_bottom_sheet.dart
> +        value: isNightMode
Can you chnage to be able to pass the color parameters so doesn't have to hard code the color or even better use the Theme

2021-01-11 23:48 UTC, onikiri2007 commented on lib/src/bottom_sheets/cupertino_bottom_sheet.dart
> +  final bool isNightMode;
isn't this nightMode should be determined by ThemeData? instead of flag passing as parameters?

2021-01-12 06:22 UTC, prayan-patel commented on lib/src/bottom_sheets/cupertino_bottom_sheet.dart
> +        value: isNightMode
Ya sure @onikiri2007 I will change it.

2021-01-14 22:58 UTC, onikiri2007 approved these changes

2021-01-15 02:43 UTC, merged